!!python/object:pdpp.tasks.standard_task.StandardTask
dep_files:
  task_2: !!python/object:pdpp.templates.dep_dataclass.dep_dataclass
    dir_list: []
    file_list:
    - df_plus_two.csv
    task_name: task_2
    task_out: output
enabled: true
language: Python
src_files:
- task_3.py
target_dir: task_3
